server:
  port: 0
spring:
  application:
    name: LEAVE-REQUESTS-SERVICE
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/


queue:
  leave-entitlements: q.leave-entitlements